### ISSUE TITLE
Routing is kinda cringe

### ISSUE THREAD

**Issue by human37** [russell-hustle/lyrical#6]
I realized this issue when you visit this [post and click on the lyrical link](https://www.linkedin.com/posts/markabraham014_lyrical-activity-6747358507433115648-hC4F). You need to refresh in order to be redirected to the landing page. I feel like it should auto detect and redirect you automatically if you are not authenticated when you visit the URL the first time. In the console you get a bunch of 401's from the Spotify API.

**Comment by evad1n** [comment]
pretty sure thats cuz mark's a dumbass and has the url with his access token. but it also highlights some other problems. Instead of checking if the url is longer than 50 characters, we should check if we were referred from spotify (document.referrer). Either that or we can try and get the token on the server working but hahah gl with that.

**Comment by human37** [comment]
Yeah, so we could either 

1. add code to check for that we were referred from Spotify
2. get mark to edit the URL in his post

Idk what is easier tbh.

**Comment by human37** [comment]
Also why is mark not a member of this organization

**Comment by evad1n** [comment]
cuz he's cringe bro... Puts it on linkedin and isn't even part of the org

**Comment by evad1n** [comment]
Fixed in PR #7 .
